spring:
  datasource:
    url: jdbc:postgresql://dpg-d7g8kf8sfn5c73a09lrg-a.oregon-postgres.render.com:5432/company_registration
    username: company_registration_user
    password: qKweUnVfFNTvjNc3w63RMJDn0Mv5QtcO
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      indent_output: true

############################################################
# LOGGING
############################################################
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG